server:
  #端口
  port: 8082


spring:
  #邮箱配置
  mail:
    #邮箱服务器地址
    host: smtp.qq.com
    #发送者邮箱地址
    username: 2590782602@qq.com
    #授权码，（在邮箱开通服务是获取）
    password: yhbbuskkhxuwdicg
    #协议
    protocol: smtp
    #编码格式
    default-encoding: utf-8
    #端口
    port: 25

  #    #协议
#    stmp:
#      socketFactoryClass: javax.net.ssl.SSLSocketFactory
#    #端口（不同邮箱端口号不同）
#    properties.mail.smtp.port: 465
#    from: 840950403@qq.com
#    properties.mail.smtp.starttls.enable: true
#    properties.mail.smtp.starttls.required: true
#    properties.mail.smtp.ssl.enable: true
#    default-encoding: utf-8
#    protocol: stmp
  rabbitmq:
    host: 192.168.180.128
    port: 5672
    username: admin
    password: 123
#    publisher-returns: true
    #开启手动确认发布
    listener:
      simple:
        acknowledge-mode: manual
#        prefetch: 100

  redis:
    #超时时间
    timeou: 10000ms
    #服务器地址
    host: 127.0.0.1
    #服务器端口
    port: 6379
    #密码
    #password: toot
    #数据库
    database: 0
    lettuce:
      pool:
        #最大连接数，默认8
        max-active: 1024
        #最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        #最大空闲连接
        max-idle: 200
        #最小空闲连接
        min-idle: 5


mybatis-plus:
  #配置Mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置MyBatis数据返回类型别名（默认别名是类名）
  type-aliases-package: com.xxxx.server.pojo
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: false